SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[Members](  
[MemberId] [int] IDENTITY(1,1) NOT NULL,  
[Name] [varchar](250) NOT NULL,  
[Age] [int] NOT NULL,  
[ImagePath] [varchar](250) NOT NULL,  

CONSTRAINT [PK_Members] PRIMARY KEY CLUSTERED  
([MemberId] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO 